### ISSUE TITLE
还可以优化下的。

### ISSUE THREAD

**Issue by TimAimee** [zhangxuyang321/XyzInfo#1]
看了您的效果，写的蛮好的。不过我发现的个问题，应该还要优化下。
比如我选择一个值在两个刻度之间。比如【190cm-191cm】，因为最少单位是1cm,此时数字显示是190cm,但是指针的方向还是在中间，没有在190cm的刻度之上。

**Comment by zhangxuyang321** [comment]
这个正在添加,最近有点忙,过段时间更新一下
